app: golden-eagle-system
services:
  - name: golden-eagle-service
    dockerfile: Dockerfile
    ports:
      - port: 8080
        http_path: "/"
    env:
      - name: CRYPTO_KEY
        secret: true
      - name: BINANCE_API_ENC
        secret: true
      - name: BINANCE_SECRET_ENC
        secret: true
    regions: [cdg]
    scaling:
      min: 1
      max: 1
