app: golden-eagle
services:
  - name: golden-eagle
    docker:
      dockerfile: Dockerfile
      context: .
    ports:
      - port: 8080
        http_path: /
    env:
      - name: TZ
        value: Asia/Riyadh
      - name: PYTHONUNBUFFERED
        value: "1"